### PR TITLE
Add files entry to package.json.

### PR DESCRIPTION
**Pull request by jamestalmage**
Removes unnecessary files from the deployed package.

Deploying unnecessary files impacts the performance of `npm install` for everyone.

See: https://github.com/insin/package-config-checker

### CODE REVIEW

**Comment by simov** [comment]
I'm usually adding the LICENSE and README files as well. Thoughts?

**Comment by jamestalmage** [comment]
LICENSE and README are included automatically (you can't NOT include them).

**Comment by simov** [comment]
Oh wow, didn't know about that :open_mouth:

**Comment by simov** [comment]
I knew only about package.json.

**Comment by jamestalmage** [comment]
thx!

**Pull request merged**
